name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
        override: true

    - name: Cache dependencies
      uses: swatinem/rust-cache@v2
    - name: Build
      run: |
        rustup update
        rustup target add wasm32-wasi
        git clone -b v0.138.6 https://github.com/zed-industries/zed.git .
        cargo xtask clippy
        cargo run --release
    - uses: actions/upload-artifact@v4
      with:
        name: my-zed
        path: ./target
    
