name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
        override: true

    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - name: Build
      run: |
        rustup update
        rustup target add wasm32-wasi
        git clone https://github.com/zed-industries/zed.git .
        cargo xtask clippy
        cargo run --release
    - uses: actions/upload-artifact@v4
      with:
        name: my-zed
        path: ./target
    
